version: "3.9"

services:
  micro-football:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro-football
    ports:
      - "3000:3000"     # Cambia a "80:3000" si querés servir directo sin proxy
    environment:
      NODE_ENV: production
    restart: unless-stopped
    # Si usás proxy reverso (Nginx/Traefik/Caddy), dejá solo la red interna y
    # publica el servicio a través del proxy:
    # networks:
    #   - proxy

# networks:
#   proxy:
#     external: true
